### ISSUE TITLE
How does the iam_role_arn get injected into the application template?

### ISSUE THREAD

**Issue by Almenon** [gitops-bridge-dev/gitops-bridge-argocd-control-plane-template#1]
In bootstrap/control-plane/addons/aws/addons-aws-csi-fsx-driver-appset.yaml there is a line of code `eks.amazonaws.com/role-arn: {{metadata.annotations.aws_fsx_csi_driver_iam_role_arn}}`. I know the metadata comes from the secret created by the gitops-bridge-bootstrap module, but I'm unclear on how argocd knows to use that secret when templating out `metadata.annotations.aws_fsx_csi_driver_iam_role_arn`.

**Comment by blakeromano** [comment]
It is from the cluster generator. The cluster generator will use the secret object for the cluster it is generating the application from. If you have cluster A and cluster B both have the label saying they want this addon, it'll generate out the application with that context. You can read more about it here https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Generators-Cluster/

**Comment by Almenon** [comment]
Ahhh, thanks. So the flow is like this, in order from top to bottom:

[main.tf](https://github.com/gitops-bridge-dev/gitops-bridge/blob/50b31110068a616370002f9b6c412cd272c42072/argocd/iac/terraform/examples/eks/hello-world/main.tf) generates metadata with ISRA ARN's, and passes that to...
[gitops-bridge-metadata](https://github.com/gitops-bridge-dev/gitops-bridge/blob/50b31110068a616370002f9b6c412cd272c42072/argocd/iac/terraform/modules/gitops-bridge-metadata/main.tf#L8), which creates the secret contents with `"argocd.argoproj.io/secret-type" = "cluster"` and a default of argocd namespace. The contents are passed to ...
[gitops_bridge_bootstrap](https://github.com/gitops-bridge-dev/gitops-bridge/blob/50b31110068a616370002f9b6c412cd272c42072/argocd/iac/terraform/modules/gitops-bridge-bootstrap/main.tf#L75), which creates the secret. Then...
ArgoCD automatically picks up the secret via the [Cluster generator](https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Generators-Cluster/).
The generator templates out ArgoCD Applications.

Is there any other way to template out custom values into ArgoCD applications that you know of? I'm curious if the Cluster Generator is the only way or if I have other options. 

Relevant: https://github.com/argoproj/argo-cd/issues/7189

**Comment by csantanapr** [comment]
Hi @Almenon,

Thanks for looking at the gitops-bridge project

Currently the argocd secret that stores the metadata in annotations, and triggers in labels is done from terraform, it really doesn't matter how the data is added to the cluster secret.

You can also take the secret and have argocd deployed it if you put the argocd secret as yaml file in this location with the cluster name as folder if will be deploy then you can edit in git https://github.com/gitops-bridge-dev/gitops-bridge-argocd-control-plane-template/tree/main/clusters

You can also store the metadata in git and extract with git generator.

There are other methods people have use like a argocd plugin and the recent applicationset plugin
For example using the [argocd vault plugin](https://argocd-vault-plugin.readthedocs.io/en/stable/) or [helm-secret](https://github.com/jkroepke/helm-secrets/wiki/ArgoCD-Integration)

For the first implementation of examples I wanted to use the most basic method that doesn't required a 3rd party plugin (enterprise customers sometimes can't use 3rd party dependencies)

There is proposal to implement in argocd [Proposal to introduce dynamic application parameter](https://github.com/argoproj/argo-cd/pull/12050) this is will be similar to the current method of extracting from cluster secret but instead from any secret/configmap

**Comment by csantanapr** [comment]
The main question was answered
