### ISSUE TITLE
Typo in default/addons/argo-cd/values.yaml

### ISSUE THREAD

**Issue by zioproto** [gitops-bridge-dev/gitops-bridge-argocd-control-plane-template#38]
Should this be `gitops-bridge`  instead of `brige` ?

https://github.com/gitops-bridge-dev/gitops-bridge-argocd-control-plane-template/blob/201f80b682b2e0f08087e0204d814d0c36a55b65/environments/default/addons/argo-cd/values.yaml#L212

**Comment by csantanapr** [comment]
Yes typo @zioproto want to send a PR?
